import Head from 'next/head'
import { useRouter } from "next/router";
import { useEffect } from "react";
import { useDispatch, useSelector } from "react-redux";
import styles from "../styles/Home.module.css";
import {
  GoogleProvider,
  FacebookProvider,
  GithubProvider,
} from "./../config/firebase/authMethod";
import { signIn } from "./../config/redux/actions/authAction";

export default function Home() {
  const router = useRouter();
  const dispatch = useDispatch();
  const globalStore = useSelector((data) => data);
  const handleAuth = (provider) => {
    dispatch(signIn(provider));
  };

  useEffect(() => {
    console.log(globalStore);
    if (globalStore.auth.dataAuth !== undefined) {
      router.push("/home");
    }
  }, [globalStore.auth.dataAuth]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Next.js <a href="https://nextjs.org">TodoApp</a>
        </h1>

        <div className={styles.grid}>
          <button
            onClick={() => handleAuth(GoogleProvider)}
            className={styles.card}
          >
            <p>Google</p>
          </button>

          <button
            onClick={() => handleAuth(FacebookProvider)}
            className={styles.card}
          >
            <p>Facebook</p>
          </button>

          <button
            onClick={() => handleAuth(GithubProvider)}
            className={styles.card}
          >
            <p>Github</p>
          </button>
        </div>
      </main>
    </div>
  );
}
